"""
Django settings for property_backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from firebase_admin import initialize_app, get_app
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

FIREBASE_APP = initialize_app()



# Load environment variables from .env file
load_dotenv()

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent
APPS_DIR = BASE_DIR / "dashboard_backend"

# Security and configuration
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# Define allowed hosts as a list derived from environment variables
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]").split(",")

# Render.com sets RENDER=true in their environment
RENDER = os.environ.get("RENDER", "False").lower() in ("true", "1", "yes")


# APPS
# ------------------------------------------------------------------------------
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    'request_id',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'debug_toolbar',
    'django_filters',
    'corsheaders',
]

LOCAL_APPS = [
    'dashboard_backend.users',  # Custom user app
    'dashboard_backend.nifty',
]
# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "request_id.middleware.RequestIdMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom exception handling middleware
    # 'property_backend.middleware.CustomExceptionHandlerMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# JWT secret key for custom token encoding
JWT_SECRET = os.environ.get('JWT_SECRET')

# Django REST framework settings with JWT authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "rest_framework.authentication.SessionAuthentication",
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    "EXCEPTION_HANDLER": "dashboard_backend.utils.rest_exception_handler.rest_exception_handler",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

# JWT settings for token-based authentication
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=28),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SECRET,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# URL configuration
ROOT_URLCONF = 'config.urls'

# Template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(APPS_DIR / "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application entry point
WSGI_APPLICATION = 'config.wsgi.application'

# Database configuration
# Support both DATABASE_URL (Render) and individual SQL_* env vars (local/Docker)
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    _db_options = {}
    if schema := os.environ.get('SQL_SCHEMA'):
        _db_options['options'] = f'-c search_path={schema},public'

    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('SQL_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('SQL_DATABASE'),
            'USER': os.environ.get('SQL_USER'),
            'PASSWORD': os.environ.get('SQL_PASSWORD'),
            'HOST': os.environ.get('SQL_HOST'),
            'PORT': os.environ.get('SQL_PORT'),
            **({'OPTIONS': _db_options} if _db_options else {}),
        }
    }

# Password validation settings
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Localization settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Twilio configuration for OTP
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")
VERIFICATION_SID = os.environ.get("TWILIO_VERIFY_SERVICE_SID")

# Agreement extraction (LLM) service base URL for extract-from-file. Example: http://localhost:8000
AGREEMENT_EXTRACTION_SERVICE_URL = os.environ.get("AGREEMENT_EXTRACTION_SERVICE_URL", "http://0.0.0.0:8000").strip() or None



# Specify custom user model
AUTH_USER_MODEL = 'users.User'  # Adjust as necessary based on your app name

# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#logging
# See https://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
# REQUEST_ID_HEADER = None
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "request_id.logging.RequestIdFilter",  # Automatically available from the package
        }
    },
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(process)d %(filename)s:%(lineno)d %(thread)d request_id=%(request_id)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_id"],
        },
    },
    "root": {
        "level": "INFO",
        "handlers": ["console"],
    },
}

# By Default swagger ui is available only to admin user(s). You can change permission classes to change that
# See more configuration options at https://drf-spectacular.readthedocs.io/en/latest/settings.html#settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Property Evaluation API",
    "DESCRIPTION": "Documentation of API endpoints of Property Evaluation API",
    "VERSION": "1.0.0",
    # "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
    "SCHEMA_PATH_PREFIX": "/api/",
    "SERVE_INCLUDE_SCHEMA": True,   #  Show the OpenAPI schema in the docs
}


INTERNAL_IPS = [
    "127.0.0.1", # needed for debugging tools 
]

# LOGIN_URL = '/login/' 

# MEDIA
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str(BASE_DIR / "media")
# https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = "/media/"


# Redis (optional - use REDIS_URL env for Docker/production)
REDIS_URL = os.environ.get("REDIS_URL")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ.get("CACHES_LOCATION", f"{REDIS_URL}/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    # Fallback to local memory cache when Redis is not available
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Celery Configuration (optional - requires Redis)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL or "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL or "redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 60  # 1 minute
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# CORS allowed origins - includes local dev and production
_cors_origins = [
    "http://localhost:5173",   # Vite dev
    "http://127.0.0.1:5173",
    "http://0.0.0.0:5173",
    "http://localhost",       # Docker (frontend on port 80)
    "http://127.0.0.1",
    "http://localhost:80",
    "http://127.0.0.1:80",
]

# Add production frontend URL from environment
FRONTEND_URL = os.environ.get("FRONTEND_URL", "").strip().rstrip("/")
if FRONTEND_URL:
    _cors_origins.append(FRONTEND_URL)

# Add any additional CORS origins from environment (comma-separated)
EXTRA_CORS_ORIGINS = os.environ.get("EXTRA_CORS_ORIGINS", "")
if EXTRA_CORS_ORIGINS:
    _cors_origins.extend([origin.strip().rstrip("/") for origin in EXTRA_CORS_ORIGINS.split(",") if origin.strip()])

CORS_ALLOWED_ORIGINS = _cors_origins

# Allow all Vercel preview URLs (*.vercel.app)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

# CORS settings for file uploads
CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = []
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
if RENDER:
    CSRF_TRUSTED_ORIGINS.extend([
        f"https://{host}" for host in ALLOWED_HOSTS if host.startswith(".")
    ])
# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]

# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

FASTAPI_BASE_URL = "http://localhost:8000"