# Generated by Django 5.2.8 on 2026-03-18 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_lastUpdateTime', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('advance', models.JSONField(default=dict)),
                ('timestamp', models.CharField(blank=True, max_length=64, null=True)),
                ('marketStatus', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('data', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'nifty_snapshot',
                'indexes': [models.Index(fields=['-captured_at'], name='nifty_snaps_capture_bb04a0_idx')],
            },
        ),
    ]
