# Generated by Django 5.2.8 on 2026-03-18 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.CharField(db_index=True, default='NIFTY', max_length=32)),
                ('expiryDate', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'option_chain_snapshot',
                'indexes': [models.Index(fields=['symbol', '-captured_at'], name='option_chai_symbol_e9c767_idx'), models.Index(fields=['symbol', 'expiryDate', '-captured_at'], name='option_chai_symbol_5842c4_idx')],
            },
        ),
    ]
