# Generated by Django 5.2.8 on 2026-03-18 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0002_optionchainsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyChartSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('indexName', models.CharField(db_index=True, default='NIFTY 50', max_length=64)),
                ('flag', models.CharField(db_index=True, max_length=8)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'nifty_chart_snapshot',
                'indexes': [models.Index(fields=['indexName', 'flag', '-captured_at'], name='nifty_chart_indexNa_43a54d_idx')],
            },
        ),
    ]
